apiVersion: v1
kind: Template
metadata:
  name: Camunda
objects:
- apiVersion: v1
  data:
    mail-config.properties: |
      # send mails via SMTP
      mail.transport.protocol=smtp

      mail.smtp.host=${SMTP_SERVER}
      mail.smtp.port=25
      mail.smtp.auth=false
      mail.smtp.ssl.enable=false
      #mail.smtp.socketFactory.port=465
      #mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

      # poll mails via IMAPS
      #mail.store.protocol=imaps

      # mail.imaps.host=imap.gmail.com
      #mail.imaps.port=993
      #mail.imaps.timeout=10000

      # additional config
      #mail.poll.folder=INBOX
      mail.sender=donotreply@gov.bc.ca
      mail.sender.alias=DoNotReply
      mail.attachment.download=true
      mail.attachment.path=attachments

      # credentials
      mail.user=
      mail.password=
  kind: ConfigMap
  metadata:
    labels:
      app: ${NAME}
    name: camunda-mail-setup
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    path: /camunda
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
      - name: web
        port: 8080
        targetPort: 8080
    selector:
      app: ${NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - ${NAME}
                topologyKey: kubernetes.io/hostname
        containers:
          - env:
            - name: JDBC_DRIVER
              value: ${DATABASE_DRIVER}
            - name: JDBC_URL
              value: jdbc:postgresql://${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/${DATABASE_NAME}
            - name: JDBC_USER
              value: ${DB_USERNAME}
            - name: JDBC_PASSWORD
              value: ${DB_PASSWORD}
            - name: WAIT_FOR
              value: ${DATABASE_SERVICE_NAME}:${DATABASE_PORT}
            - name: KEYCLOAK_URL
              value: ${KEYCLOAK_URL}
            - name: KEYCLOAK_URL_REALM
              value: ${KEYCLOAK_REALM}
            - name: KEYCLOAK_CLIENTID
              value: ${KEYCLOAK_CLIENTID}
            - name: KEYCLOAK_CLIENTSECRET
              value: ${KEYCLOAK_CLIENTSECRET}
            - name: DEBUG
              value: "False"
            - name: MAIL_CONFIG
              value: /app/mail-config.properties
            - name: ANALYTICS_DB_JDBCURL
              value: ${ANALYTICS_DB_JDBCURL}
            - name: ANALYTICS_DB_USERNAME
              value: ${ANALYTICS_DB_USERNAME}
            - name: ANALYTICS_DB_PASSWORD
              value: ${ANALYTICS_DB_PASSWORD}
            - name: ANALYTICS_DB_DRIVER
              value: ${ANALYTICS_DB_DRIVER}
            - name: FORMBUILDER_PIPELINE_USERNAME
              value: ${FORMBUILDER_PIPELINE_USERNAME}
            - name: FORMBUILDER_PIPELINE_PASSWORD
              value: ${FORMBUILDER_PIPELINE_PASSWORD}
            - name: FORMBUILDER_PIPELINE_BPM_URL
              value: ${FORMBUILDER_PIPELINE_BPM_URL}
            - name: TZ
              value: UTC
            - name: APP_ROOT_LOG_FLAG
              value: ${APP_ROOT_LOG_FLAG}
            - name: BPM_HISTORY_LEVEL
              value: ${BPM_HISTORY_LEVEL}
            - name: SESSION_STORE_TYPE
              value: jdbc
            - name: SESSION_STORE_TIMEOUT
              value: "28800"
            - name: JAVA_SYSTEM_PROPERTIES
              value: -Xmx2048m
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /camunda/actuator/health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            name: ${NAME}
            ports:
              - containerPort: 8080
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /camunda/actuator/health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 60
              successThreshold: 1
              timeoutSeconds: 3
            resources:
              limits:
                cpu: 750m
                memory: 4Gi
              requests:
                cpu: 200m
                memory: 2Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /app/mail-config.properties
                name: camunda-mail-volume
                subPath: mail-config.properties
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              items:
                - key: mail-config.properties
                  path: mail-config.properties
              name: camunda-mail-setup
            name: camunda-mail-volume
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:${IMAGE_TAG}
          namespace: ${TOOLS_WORKSPACE}
      type: ImageChange
parameters:
- name: NAME
  description: The name for all created objects.
  required: true
  value: camunda
- name: IMAGE_TAG
  description: The image tag to pull for the deployment.
  required: true
- name: TOOLS_WORKSPACE
  description: The location for your image streams (Tools Workspace).
  required: true
- name: SMTP_SERVER
  description: The domain name of the SMTP server for sending emails.
  required: true
- name: DATABASE_DRIVER
  description: The database driver used to connnect to the persistent storage.
  required: true
  value: org.postgresql.Driver
- name: DATABASE_SERVICE_NAME
  description: The Service name used to connect to the database.
  required: true
  value: patroni-persistent-master
- name: DATABASE_NAME
  description: The name of the database to connect to.
  required: true
  value: camunda
- name: DATABASE_PORT
  description: The port that the database is running on.
  required: true
  value: "5432"
- name: APPLICATION_DOMAIN
  description: The exposed hostname that will route to the Vue application. IE. workflow.<domain>.com
  required: true
- name: DB_USERNAME
  description: The postgres database username.
  required: true  
- name: DB_PASSWORD
  description: The postgres database password.
  required: true
- name: KEYCLOAK_URL
  description: The URL used to connnect to the OIDC provider.
  required: true
- name: KEYCLOAK_REALM
  description: The realm used to connnect to the OIDC provider.
  required: true
- name: KEYCLOAK_CLIENTID
  description: The clientid used to connnect to the OIDC provider.
  required: true
- name: KEYCLOAK_CLIENTSECRET
  description: The client secret used to connnect to the OIDC provider.
  required: true
- name: ANALYTICS_DB_JDBCURL
  description: The database url used to connnect to the analytics database.
  required: true
- name: ANALYTICS_DB_USERNAME
  description: The database username used to connnect to the analytics database.
  required: true
  value:
- name: ANALYTICS_DB_PASSWORD
  description: The database password used to connnect to the analytics database.
  required: true
  value:
- name: ANALYTICS_DB_DRIVER
  description: The database driver used to connnect to the analytics database.
  required: true
  value: org.postgresql.Driver
- name: FORMBUILDER_PIPELINE_BPM_URL
  description: The URL for the formbuilder connection 
  required: true
- name: FORMBUILDER_PIPELINE_USERNAME
  description: The username for the formbuilder connection
  required: true
- name: FORMBUILDER_PIPELINE_PASSWORD
  description: The password for the formbuilder connection.
  required: true
- name: APP_ROOT_LOG_FLAG
  description: The log4j logging level to use for the application logs.
  required: true
  value: ERROR
- name: BPM_HISTORY_LEVEL
  description: The history level used in Camunda BPM.
  required: true
  value: auto
- name: SESSION_STORE_TYPE
  description: Session management for Multiple Pod implementations
  required: true
  value: none