apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: forms-flow-bpm
objects:
  - apiVersion: v1
    data:
      mail-config.properties: |
        # send mails via SMTP
        mail.transport.protocol=smtp
        mail.smtp.host=${SMTP_SERVER}
        mail.smtp.port=25
        mail.smtp.auth=false
        mail.smtp.ssl.enable=false
        #mail.smtp.socketFactory.port=465
        #mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
        # poll mails via IMAPS
        #mail.store.protocol=imaps
        # mail.imaps.host=imap.gmail.com
        #mail.imaps.port=993
        #mail.imaps.timeout=10000
        # additional config
        #mail.poll.folder=INBOX
        mail.sender=donotreply@gov.bc.ca
        mail.sender.alias=DoNotReply
        mail.attachment.download=true
        mail.attachment.path=attachments
        # credentials
        mail.user=
        mail.password=
    kind: ConfigMap
    metadata:
      labels:
        app: ${NAME}
        app-group: forms-flow-ai
      name: ${NAME}-mail-config
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}
        app-group: forms-flow-ai
      name: ${NAME}
    spec:
      host: ${CAMUNDA_URL}
      path: /camunda
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
      wildcardPolicy: None
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}
        app-group: forms-flow-ai
      name: ${NAME}
    spec:
      ports:
        - name: web
          port: 8080
          targetPort: 8080
      selector:
        app: ${NAME}
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
      labels:
        app: ${NAME}
        app-group: forms-flow-ai
      name: ${NAME}
    spec:
      replicas: 2
      revisionHistoryLimit: 10
      selector:
        app: ${NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}
            app-group: forms-flow-ai
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - ${NAME}
                  topologyKey: kubernetes.io/hostname
          containers:
            - env:
                - name: APP_SECURITY_ORIGIN
                  value: '*'
                - name: CAMUNDA_JDBC_URL
                  value: jdbc:postgresql://${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/${DATABASE_NAME}
                - name: WAIT_FOR
                  value: ${DATABASE_SERVICE_NAME}:${DATABASE_PORT}
                - name: KEYCLOAK_URL
                  value: ${KEYCLOAK_URL}
                - name: KEYCLOAK_URL_REALM
                  valueFrom:
                    secretKeyRef:
                      key: KEYCLOAK_REALM
                      name: ${FORMIO_SECRET}
                - name: KEYCLOAK_CLIENTID
                  valueFrom:
                    secretKeyRef:
                      key: FFA_BPM_CLIENT_ID
                      name: ${FORMIO_SECRET}
                - name: KEYCLOAK_CLIENTSECRET
                  valueFrom:
                    secretKeyRef:
                      key: FFA_BPM_CLIENT_SECRET
                      name: ${FORMIO_SECRET}
                - name: MAIL_CONFIG
                  value: /app/mail-config.properties
                - name: TZ
                  value: UTC
                - name: CAMUNDA_JDBC_DRIVER
                  value: ${CAMUNDA_JDBC_DRIVER}
                - name: FORMIO_ROOT_EMAIL
                  valueFrom:
                    secretKeyRef:
                      key: FORMIO_ROOT_EMAIL
                      name: ${FORMIO_SECRET}
                - name: FORMIO_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: FORMIO_ROOT_PASSWORD
                      name: ${FORMIO_SECRET}
                - name: CAMUNDA_JDBC_USER
                  valueFrom:
                    secretKeyRef:
                      key: DB_USERNAME
                      name: ${FORMIO_SECRET}
                - name: CAMUNDA_JDBC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: DB_PASSWORD
                      name: '${FORMIO_SECRET}'
                - name: CAMUNDA_JDBC_DB
                  value: ${DATABASE_NAME}
                - name: FORMSFLOW_API_URL
                  value: ${FORMSFLOW_API_URL}
                - name: FORMIO_URL
                  value: ${FORMIO_URL}
                - name: WEBSOCKET_ENCRYPT_KEY
                  value: ${WEBSOCKET_ENCRYPT_KEY}
                - name: WEBSOCKET_SECURITY_ORIGIN
                  value: ${WEBSOCKET_SECURITY_ORIGIN}
                - name: WEBSOCKET_BROKER_HOST
                  value: ${WEBSOCKET_BROKER_HOST}
                - name: WEBSOCKET_BROKER_PASSCODE
                  value: ${WEBSOCKET_BROKER_PASSCODE}
                - name: WEBSOCKET_BROKER_PORT
                  value: ${WEBSOCKET_BROKER_PORT}
                - name: WEBSOCKET_MESSAGE_TYPE
                  value: ${WEBSOCKET_MESSAGE_TYPE}
                - name: CAMUNDA_APP_ROOT_LOG_FLAG
                  value: ERROR
                - name: CAMUNDA_METRICS_FLAG
                  value: 'false'
                - name: DATA_BUFFER_SIZE
                  value: ${DATA_BUFFER_SIZE}
                - name: IDENTITY_PROVIDER_MAX_RESULT_SIZE
                  value: '650'
                - name: CAMUNDA_ANALYTICS_JDBC_DRIVER
                  value: ${CAMUNDA_ANALYTICS_JDBC_DRIVER}
                - name: CAMUNDA_ANALYTICS_JDBC_URL
                  value: ${CAMUNDA_ANALYTICS_JDBC_URL}
                - name: CAMUNDA_ANALYTICS_JDBC_USER
                  valueFrom:
                    secretKeyRef:
                      key: camunda_analytics_jdbc_user
                      name: ${FORMIO_SECRET}
                - name: CAMUNDA_ANALYTICS_JDBC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: camunda_analytics_jdbc_password
                      name: ${FORMIO_SECRET}
                - name: CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL
                  value: ${CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL}
                - name: CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: camunda_formbuilder_pipeline_username
                      name: ${FORMIO_SECRET}
                - name: CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: camunda_formbuilder_pipeline_password
                      name: ${FORMIO_SECRET}
              imagePullPolicy: Always
              livenessProbe:
                tcpSocket:
                  port: 8080
                initialDelaySeconds: 30
                timeoutSeconds: 3
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /camunda/actuator/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 3
                periodSeconds: 60
                successThreshold: 1
                failureThreshold: 3
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - name: ${NAME}-mail-config              
                  mountPath: /app/mail-config.properties
                  subPath: mail-config.properties
              name: ${NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              image: ${IMAGE_NAMESPACE}/${NAME}:${TAG_NAME}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: ${NAME}-mail-config
              configMap:
                name: ${NAME}-mail-config
                items:
                  - key: mail-config.properties
                    path: mail-config.properties
                defaultMode: 420
      test: false
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - ${NAME}
          from:
            kind: ImageStreamTag
            name: ${NAME}:${IMAGE_TAG}
            namespace: ${TOOLS_WORKSPACE}
        type: ImageChange
parameters:
  - name: NAME
    description: The name for all created objects.
    value: forms-flow-bpm
  - name: FORMIO_SECRET
    description: Secrets are referred from this.
    value: forms-flow-ai
  - name: IMAGE_TAG
    description: The image tag to pull for the deployment.
    required: true
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 500m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 1000m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 2Gi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 4Gi
  - name: TOOLS_WORKSPACE
    description: The location for your image streams (Tools Workspace).
    required: true
  - name: SMTP_SERVER
    description: The domain name of the SMTP server for sending emails.
    required: true
  - name: DATABASE_SERVICE_NAME
    description: The Service name used to connect to the database.
    required: true
  - name: DATABASE_NAME
    description: The name of the database to connect to.
    required: true
  - name: DATABASE_PORT
    description: The port that the database is running on.
    value: "5432"
  - name: CAMUNDA_JDBC_DRIVER
    description: CAMUNDA_JDBC_DRIVER
    value: "org.postgresql.Driver"
  - name: FORMSFLOW_API_URL
    description: FORMSFLOW_API_URL
    required: true
  - name: FORMIO_URL
    description: FORMIO_URL
    required: true
  - name: CAMUNDA_URL
    displayName: CAMUNDA_URL
    description: Route to access Camunda
    required: true
  - name: WEBSOCKET_ENCRYPT_KEY
    description: WEBSOCKET_ENCRYPT_KEY
    required: true
  - name: WEBSOCKET_SECURITY_ORIGIN
    description: WEBSOCKET_SECURITY_ORIGIN
    required: true
  - name: WEBSOCKET_BROKER_HOST
    description: redis service name
    required: true
  - name: WEBSOCKET_BROKER_PASSCODE
    description: redis password
    required: true
  - name: WEBSOCKET_BROKER_PORT
    description: redis port
    value: "6379"
  - name: WEBSOCKET_MESSAGE_TYPE
    description: redis port
    required: true
    value: "TASK_EVENT"
  - name: KEYCLOAK_URL
    description: Keycloak URL 
    required: true
  - name: DATA_BUFFER_SIZE
    description: Size of attachments
    required: false
    value: "10"
  - name: CAMUNDA_ANALYTICS_JDBC_URL
    description: CAMUNDA_ANALYTICS_JDBC_URL
    required: true
  - name: CAMUNDA_ANALYTICS_JDBC_DRIVER
    description: CAMUNDA_ANALYTICS_JDBC_DRIVER
    required: true
  - name: CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL
    description: CAMUNDA_FORMBUILDER_PIPELINE_BPM_URL
    required: true