apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    type: Opaque
    stringData:
      BPM_API_BASE: "${BPM_API_BASE}"
      BPM_TOKEN_API: "${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USERNAME: "${DB_USERNAME}"
      FFA_BPM_CLIENT_ID: "${FFA_BPM_CLIENT_ID}"
      FFA_BPM_CLIENT_SECRET: "${FFA_BPM_CLIENT_SECRET}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      KEYCLOAK_URL: "${KEYCLOAK_URL}"
      camunda_formbuilder_pipeline_username: "${CAMUNDA_FORMBUILDER_PIPELINE_USERNAME}"
      FORMIO_ROOT_EMAIL: "${FORMIO_ROOT_EMAIL}"
      FORMIO_ROOT_PASSWORD: "${FORMIO_ROOT_PASSWORD}"
      camunda_formbuilder_pipeline_password: "${CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD}"
      camunda_analytics_jdbc_user: "${CAMUNDA_ANALYTICS_JDBC_USER}"
      camunda_analytics_jdbc_password: "${CAMUNDA_ANALYTICS_JDBC_PASSWORD}"
      JWT_OIDC_ALGORITHMS: RS256
      JWT_OIDC_AUDIENCE: forms-flow-web
      JWT_OIDC_CACHING_ENABLED: "True"
      JWT_OIDC_ISSUER: "${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}"
      JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
      JWT_OIDC_JWKS_URI: '${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs'
      JWT_OIDC_WELL_KNOWN_CONFIG: "${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration"
      WEB_API_BASE_URL: "${WEB_API_BASE_URL}"
      DEBUG: formio:*
      MONGODB_URI: "${MONGODB_URI}"
      NODE_CONFIG: '{"mongo": "${MONGODB_URI}"}'
      API_DATABASE_URL: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/${API_DATABASE_NAME}"
      INSIGHT_API_KEY: "${INSIGHT_API_KEY}"
      INSIGHT_API_URL: "${INSIGHT_API_URL}"
      FORMIO_JWT_SECRET: "${FORMIO_JWT_SECRET}"
parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: forms-flow-ai
  - name: FORMIO_ROOT_EMAIL
    description: FORMIO_ROOT_EMAIL
    required: true
  - name: FORMIO_ROOT_PASSWORD
    description: FORMIO_ROOT_PASSWORD
    required: true
  - name: CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
    description: CAMUNDA_FORMBUILDER_PIPELINE_USERNAME
    required: true
  - name: CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
    description: CAMUNDA_FORMBUILDER_PIPELINE_PASSWORD
    required: true
  - name: CAMUNDA_ANALYTICS_JDBC_USER
    description: CAMUNDA_ANALYTICS_JDBC_USER
    required: true
  - name: CAMUNDA_ANALYTICS_JDBC_PASSWORD
    description: CAMUNDA_ANALYTICS_JDBC_PASSWORD
    required: true
  - name: DB_USERNAME
    displayName: DB_USERNAME
    description: Postgres Database details
    required: true
  - name: DB_PASSWORD
    displayName: DB_PASSWORD
    description: Postgres Database details
    required: true
  - name: FFA_BPM_CLIENT_ID
    displayName: FFA_BPM_CLIENT_ID
    description: FFA_BPM_CLIENT_ID
    required: true
  - name: FFA_BPM_CLIENT_SECRET
    displayName: FFA_BPM_CLIENT_SECRET
    description: FFA_BPM_CLIENT_SECRET
    required: true
  - name: KEYCLOAK_URL
    displayName: KEYCLOAK_URL
    description: KEYCLOAK_URL
    required: true
  - name: KEYCLOAK_REALM
    displayName: KEYCLOAK_REALM
    description: KEYCLOAK_REALM
    required: true
  - name: WEB_API_BASE_URL
    description: WEB_API_BASE_URL
    required: true
  - name: DATABASE_SERVICE_NAME
    description: DATABASE_SERVICE_NAME
    required: true
  - name: DATABASE_PORT
    description: DATABASE_PORT
    required: true
  - name: API_DATABASE_NAME
    description: API DATABASE_NAME
    required: true
  - name: MONGODB_URI
    description: MONGODB_URI
    required: true
  - name: BPM_API_BASE
    description: BPM_API_BASE
    required: true
  - name: INSIGHT_API_KEY
    description: Redash API KEY
    required: true
  - name: INSIGHT_API_URL
    description: Redash URL
    required: true
  - name: FORMIO_JWT_SECRET
    description: FORM IO SECRET
    required: true
