apiVersion: v1
kind: Template
labels:
  template: wt-reverse-proxy-api
  app.kubernetes.io/part-of: TheQ
metadata:
  name: wt-reverse-proxy-api
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: "Exposes and load balances the api pods"
      name: "${API_NAME}"
      labels:
        app: "${API_NAME}"
    spec:
      ports:
        - name: web
          port: 5001
          targetPort: 5001
      selector:
        app: "${API_NAME}"
  - apiVersion: v1
    kind: Route
    metadata:
      name: "${API_NAME}"
    spec:
      host: "${API_APPLICATION_DOMAIN}"
      path: /ReportServer
      to:
        kind: Service
        name: "${API_NAME}"
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        description: "Defines how to deploy the application server"
        template.alpha.openshift.io/wait-for-ready: "true"
      name: "${API_NAME}"
    spec:
      replicas: 2
      selector:
        name: ${API_NAME}
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 120
          maxSurge: 2
          maxUnavailable: 1
        resources: {}
        activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            app: "${API_NAME}"
            name: "${API_NAME}"
        spec:
          containers:
            - name: "${API_NAME}"
              image: " "
              env:
                - name: APP_CONFIG
                  value: gunicorn_config.py
                - name: FLASK_ENV
                  value: "${FLASK_ENV}"
                - name: APP_MODULE
                  value: wsgi
                - name: SECRET_KEY
                  value: "${SECRET_KEY}"
                - name: SERVER_NAME
                  value: "${API_APPLICATION_DOMAIN}"
                - name: JWT_OIDC_WELL_KNOWN_CONFIG
                  value: "${JWT_OIDC_WELL_KNOWN_CONFIG}"
                - name: JWT_OIDC_ALGORITHMS
                  value: "RS256"
                - name: JWT_OIDC_AUDIENCE
                  value: "${JWT_OIDC_AUDIENCE}"
                - name: JWT_OIDC_CLIENT_SECRET
                  value: "${AUTH_CLIENT_SECRET}"
                - name: JWT_OIDC_CACHING_ENABLED
                  value: "True"
                - name: JWT_OIDC_JWKS_CACHE_TIMEOUT
                  value: "300"
                - name: SSRS_SERVER
                  value: "${SSRS_SERVER}"
                - name: SSRS_BASE_URI
                  value: "${SSRS_BASE_URI}"
                - name: SSRS_SYSTEM_USER
                  value: "${SSRS_SYSTEM_USER}"
                - name: SSRS_SYSTEM_CODE
                  value: "${SSRS_SYSTEM_CODE}"
                - name: INCLUDE_AUTH
                  value: "${INCLUDE_AUTH}"
                - name: PRINT_ENABLE
                  value: "false"
                - name: LOG_BASIC
                  value: WARNING
                - name: LOG_ROOT
                  value: WARNING
              ports:
                - containerPort: 5001
              readinessProbe:
                httpGet:
                  path: /api/v1/healthz
                  port: 5001
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              name: ${API_NAME}
              livenessProbe:
                httpGet:
                  path: /api/v1/readyz
                  port: 5001
                  scheme: HTTP
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 400m
                  memory: 400Mi
                limits:
                  cpu: '1'
                  memory: 600Mi
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - "${API_NAME}"
                  topologyKey: kubernetes.io/hostname
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${API_NAME}"
            from:
              kind: ImageStreamTag
              namespace: "${TOOLS_WORKSPACE}"
              name: "${API_NAME}:${API_IMAGE_TAG}"
parameters:
  - name: API_NAME
    displayName: Name
    description: "Name of the flask application"
    required: true
    value: "wt-reverse-proxy-api"
  - name: API_APPLICATION_DOMAIN
    description: "The exposed hostname that will route to the Flask service"
    required: true
    value: ""
  - name: FLASK_ENV
    description: "The configuration object that should be loaded for this deployment."
    required: true
    value: "development"
  - name: API_IMAGE_TAG
    description: "The tag to use when deploying"
    required: true
    value: "latest"
  - name: TOOLS_WORKSPACE
    description: "IMAGE STREAM WORKSPACE LOCATION"
    required: true
    value: ""
  - name: SECRET_KEY
    description: "Key required for Flask"
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: JWT_OIDC_WELL_KNOWN_CONFIG
    description: "Keycloak config location"
    required: true
  - name: JWT_OIDC_AUDIENCE
    description: "Keycloak Audience"
    required: true
  - name: AUTH_CLIENT_SECRET
    description: "Keycloak client secret"
    required: true
  - name: SSRS_SERVER
    description: "SSRS server"
    required: true
  - name: SSRS_BASE_URI
    description: "The base URI for the report server such as Report Server"
    required: true
  - name: SSRS_SYSTEM_USER
    description: "SSRS user"
    required: true
  - name: SSRS_SYSTEM_CODE
    description: "SSRS system code"
    required: true
  - name: INCLUDE_AUTH
    description: "True/False, does the reverse proxy require auth"
    required: true
